### ISSUE TITLE
Microsoft authorization fail

### ISSUE THREAD

**Issue by maxsupermanhd** [adepierre/Botcraft#40] opened 2021-07-12 00:17 UTC
Today I tried to use my Microsoft account and was greeted with 400 Bad request with contents `{"error":"IllegalArgumentException","errorMessage":"Access Token can not be null or empty."}`, however all tokens were in place and printing before executing request showed them perfectly fine.

Maybe fields are named wrong or it is missing one of them? How can I debug it further or find docs on this @adepierre?

**Comment by adepierre** [comment] 2021-07-12 00:39
Well you were the one finding out the token thing to connect with a Microsoft account in the first place so I assume you know as much -if not more- than me about that. All the doc I'm aware of is the [wiki](https://wiki.vg/Microsoft_Authentication_Scheme). As I don't have a microsoft account, there is not much I can do/test on my side.

**Comment by adepierre** [comment] 2021-07-20 00:25
Any news about this? Is this issue still present?

**Comment by maxsupermanhd** [comment] 2021-07-27 04:09
Yep, now launcher does not store token in json. We have to implement this multistep Microsoft oauth flow.

**Comment by adepierre** [comment] 2021-07-27 10:28
According to [this entry](https://bugs.mojang.com/browse/MCL-18924) in the bug tracker, it might just be a rename from ``clientToken`` to ``mojangClientToken``. Could you check your ``launcher_accounts.json`` to see if this is the case?

**Comment by adepierre** [comment] 2021-07-27 15:44
I've just found an accessToken in ``launcher_profiles.json``, could you confirm it's also present with a Microsoft account? 

If so it should be easy to grab it from there.

**Comment by maxsupermanhd** [comment] 2021-07-28 22:56
Yep, absolutely confirm however can not really reply to bug on bug tracker because have no account registered. Anyhow - I went and implemented oauth method in golang already, now I am polishing flow and error catching and hope I will bring it as pure auth flow soon. It should cache auth token tho and we don't have solution for that yet and also I just can not work with picojson for some reason but tldr is that they use device oauth flow that outsources browser from a user and pools endpoint for a code and then it continues as normal.

**Comment by adepierre** [comment] 2021-07-28 23:24
There are a *lot* of information in your message, I'm not sure I've understood all of them, but I'm happy for you that you succeded to implement your auth flow in go.

If your code is public, please don't hesitate to share it so I can take a look and see if I can transpose it in C++ for botcraft 🙂

**Comment by adepierre** [comment] 2021-08-07 01:36
I've looked once again to implement the full workflow, and I think it's doable with the exception of the browser part. There are basically two solutions: either integrating a browser view inside botcraft or calling the default browser on the computer. But the first option seems to be an overkill, and with the second I can't figure out how to get back the result from the browser (and it would prevent using Botcraft on headless servers so not a good option either). The last solution I read about was to use an external oauth flow, asking the permission on a different device than the one the connection is made (I think that's what you mentionned in the end of your message, but I'm not sure I understood well).  But I haven't found any good documentation or example about that process or how to use it in a similar usecase than Botcraft.

Anyway, I've also found a (manual) way to retrieve the accessToken and restore the ability to login using the json file in the meantime. @maxsupermanhd could you check this [md file](../blob/master/launcher_json_connection.md) and let me know if it at least allows you to connect again?

**Comment by maxsupermanhd** [comment] 2021-08-07 05:53
Want me to solve this issue?

**Comment by adepierre** [comment] 2021-08-07 13:50
Well either that, or at least showing me your working solution so I can try to reproduce it.

**Comment by maxsupermanhd** [comment] 2021-08-07 21:46
Can I link Botcraft with CURL for HTTP requests? What is present in Authentifer.cpp is not acceptable...

**Comment by adepierre** [comment] 2021-08-07 21:48
What do you mean not acceptable?

**Comment by maxsupermanhd** [comment] 2021-08-07 22:08
This flow requires a lot of HTTP requests, about 6 or something near that number. Fitting in `SendPostRequest` everything required is beyond my point of effort, there is a lot of libraries for doing exactly that. Making a lot of functions from scratch to accomplish such a simple tasks is equal as flooding codebase with unused stuff.
Of course I can do that but it will require much more effort rather than just including CURL.
Bare minimum requirements for Microsoft auth flow are following: sending HTTPS requests (POST and GET) with custom headers, SSL settings and messages with `application/x-www-form-urlencoded` format. There is no way I am reimplementing like half of proper HTTP library like one that I mentioned earlier.

**Comment by adepierre** [comment] 2021-08-07 22:17
Well all I need is a working example to build on. I've asked if you could share your go code, you didn't respond so I assumed your code was not open source. If you want to redo the job in C++ with curl just do it and I'll try to adapt it later.

At this point I'm just stuck because I can't find any example of the flow, and I can't test things myself as I don't own a microsoft account.

**Comment by maxsupermanhd** [comment] 2021-08-07 22:21
> you didn't respond so I assumed your code was not open source
Much wrong, I thought you checked it out and gave up, I have `go-mc-ms-auth` repo that has full flow implemented.

**Comment by adepierre** [comment] 2021-08-07 22:28
My bad, I misunderstood you, I'll check it out and see if I can implement it.

**Comment by maxsupermanhd** [comment] 2021-08-20 10:45
News?

**Comment by adepierre** [comment] 2021-08-20 11:47
Well, I opened [an issue](https://github.com/maxsupermanhd/go-mc-ms-auth/issues/2) on your repo because there are still things that I can't figure out from your code. But no answer so far.

**Comment by adepierre** [comment] 2021-09-03 19:34
Hey @maxsupermanhd 

I've implemented the Microsoft auth flow following your repo, I've also added a link to your code as it helped me a lot. It's currently in  branch ``msa``. As I don't have an account I haven't been able to test it past the XSTS step, but it worked so far.

Coud you confirm me that the full flow is working with your Microsoft account? Thanks!

**Comment by maxsupermanhd** [comment] 2021-09-03 22:02
Yes, I see, from the first look it is good however I would like to test everything. By everything I mean even unexpected authentication scenarios. I also have some friends that do have original Microsoft, original Mojang and migrated accounts but I am afraid it can take a bit for them to figure stuff out. I will mention you if there will be any issues.

**Comment by adepierre** [comment] 2021-09-03 22:33
Yeah sure, you can close this issue once you've confirmed everything works fine so I can merge the branch into master.

**Comment by maxsupermanhd** [comment] 2021-09-04 13:58
Also, in my """example""" there was cache only for microsoft token but that *does not* mean that other tokens should not be cached. If you try to log-in like 5 times in a row you will be rate limited in MC step (get `429 Too Many Requests`). Basically every token that has expire date present (and it is not like 10 seconds) must be cached.

**Comment by maxsupermanhd** [comment] 2021-09-04 14:21
I opened PR with the only bug I found so far but doubt it will be alone for long

**Comment by adepierre** [comment] 2021-09-04 14:48
I'll try to integrate the fix as you submit them so people cloning can test with latest fix too.

**Comment by adepierre** [comment] 2021-09-21 09:08
@maxsupermanhd hello there!

Have you been able to test the connection flow with all the configuration you wanted to yet?

**Comment by maxsupermanhd** [comment] 2021-09-21 18:13
Eh, idunno, I tested it for a while but have no idea on what can go wrong. Except obviously everything that can go wrong like network errors and all that external problem causing sources

**Comment by adepierre** [comment] 2021-09-22 07:15
Alright, I'll try to merge it into master soon then. I'll keep in mind the caching issue, but I think this should be addressed separately as it also concerns the Mojang auth.

**Comment by adepierre** [comment] 2021-09-22 18:05
Fixed with latest commit. Thanks once again for your help on this!

**Closed by adepierre** 2021-09-22 18:05 UTC
