### ISSUE TITLE
Botcraft doesn't seem to connect in anyway - status code 403

### ISSUE THREAD

**Issue by Day-OS** [adepierre/Botcraft#26] opened 2021-03-18 14:48 UTC
So I have everything built and compiled, but the code from the examples don't connect to any server at all. 
I'm running both the examples binaries and the server at an Ubuntu 18.04.5 LTS. both are using protocol 498 (1.14.4)

## 1. If I don't put arguments, it connects but automatically disconnects after.
![a](https://i.imgur.com/2tHF08l.png)
Console:
```
root@dayos:/usr/local/bin# ./2_ChatCommandExample
No command arguments. Using default options.
Usage: 2_ChatCommandExample [address](127.0.0.1:25565) [login](BCChatCommand) [password]()
Loading blocks from file...
Done!
Loading biomes from file...
Done!
Loading items from file...
Done!
Clearing cache from memory...
Done!
Known commands:
    Pathfinding to position:
        name goto x y z
    Stop current pathfinding:
        name stop
    Check perimeter for spawnable blocks and save spawnable positions to file:
        name check_perimeter [x y z (default = player position)] radius (default = 128) [check_lighting (default = true)]
    Disconnect:
        name die
    Place a block:
        name place_block minecraft:item x y z
    Interact (right click) a block:
        name interact x y z
Starting connection process
Trying to connect to 127.0.0.1:25565
Connected to server.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Not enough input in ReadString
Aborted (core dumped)
```

## 2. If I put the default options as arguments at those same files (but changing the password, as the lack of it returns the first error), it doesn't connect at all
```
root@dayos:/usr/local/bin# ./2_ChatCommandExample 127.0.0.1:25565 BCChatCommand password
Loading blocks from file...
Done!
Loading biomes from file...
Done!
Loading items from file...
Done!
Clearing cache from memory...
Done!
Known commands:
    Pathfinding to position:
        name goto x y z
    Stop current pathfinding:
        name stop
    Check perimeter for spawnable blocks and save spawnable positions to file:
        name check_perimeter [x y z (default = player position)] radius (default = 128) [check_lighting (default = true)]
    Disconnect:
        name die
    Place a block:
        name place_block minecraft:item x y z
    Interact (right click) a block:
        name interact x y z
Starting connection process
Trying to connect to 127.0.0.1:25565
Connected to server.
Authentication response returned with status code 403
```
## 3. 1_UserControlledExample seems to work, but it doesn't connect either
Console:
```
root@dayos:/usr/local/bin# ./1_UserControlledExample 0 127.0.0.1:25565 BCUserControl password
Warning, your version of botcraft hasn't been compiled with GUI enabled, setting use_renderer_ to false
Loading blocks from file...
Done!
Loading biomes from file...
Done!
Loading items from file...
Done!
Clearing cache from memory...
Done!
Client created!
Creating world...
Done!
```
I'm assuming that it might be because I'm not using GUI, but I found this relevant anyway.

**Comment by adepierre** [comment] 2021-03-18 15:02
Thanks for the report, I'll try to reproduce on my side.

For your third point, you set the ``online`` parameter to 0 in the command line. It means that you don't connect to a server but instead create a local world. Basically it's just an empty world with one of each existing blocks to test rendering and physics.

**Comment by adepierre** [comment] 2021-03-18 15:50
That was just a small error in the protocol definition for 1.14.X versions. Should be good now.

**Comment by Day-OS** [comment] 2021-03-18 22:29
It returns this error now:
```
./0_HelloWorld: symbol lookup error: ./0_HelloWorld: undefined symbol: _ZN8Botcraft10BaseClient7ConnectERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_
```

**Comment by adepierre** [comment] 2021-03-18 22:33
That's weird. Is that a fresh build?

**Comment by Day-OS** [comment] 2021-03-18 22:35
yes, I did all steps from the beginning

**Comment by adepierre** [comment] 2021-03-18 22:46
Demangling the symbol name shows that it does not find the BaseClient::Connect(string, string) method (https://github.com/adepierre/Botcraft/blob/78793e1a8cde90882a48c5c706d8282df3af94c3/botcraft/src/Game/BaseClient.cpp#L64). I added that just after ee3a927 to add Microsoft account support.

Could you try to checkout to this commit (i.e. revert one commit back) to see if it's better?

Make sure any intermediate build files are deleted before starting the build process. I strongly suspect that your compiler is trying to use an older version of the compiled library (without the BaseClient::Connect) method with a newer version of the main.cpp.

**Comment by Day-OS** [comment] 2021-03-18 23:27
It works like earlier, status code 403 and all.

**Comment by adepierre** [comment] 2021-03-18 23:29
What? You still got the ``Not enough input in ReadString`` even with the fix?

Please detail what you did and what error you get exactly.

**Comment by Day-OS** [comment] 2021-03-19 13:35
Yes, the same error.

I made everything from ground zero, cloned the repository, reverted it to one commit back, compiled everything again, and there was the error.

```
root@dayos:~/Botcraft# git branch
* (HEAD detached at ee3a927)
  master
```
And I'm sure that it changed to this commit as the `./0_HelloWorld: symbol lookup error: ./0_HelloWorld: undefined symbol: _ZN8Botcraft10BaseClient7ConnectERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_` disappeared.

**Comment by adepierre** [comment] 2021-03-19 13:55
Can't reproduce on my side with a server on 1.14.4. Any way you could find out from which file is the error coming from?

**Comment by Day-OS** [comment] 2021-03-19 14:04
I couldn't find any, but it seems like it's only related with 1.14.4. I've just tested with 1.16.5 and the same happens.
I've tried both local and external servers that were with online mode off.
The Ubuntu that I said is on a VPS. Maybe there's something related with firewall or something like that?

**Comment by adepierre** [comment] 2021-03-19 14:42
I don't think so because ``ReadString`` is called to read data from packets. So if there is an error in it, it means that you receive some data, and it tries to read them.

**Comment by adepierre** [comment] 2021-03-19 17:56
Just thought about it, are you testing it with fresh empty servers or real ones? If they are real servers it could come from a packet that is not sent in a freshly created server.

**Comment by Day-OS** [comment] 2021-03-19 18:59
I'm testing in both. About the created ones, I'm using vanilla and paper during tests.

**Comment by adepierre** [comment] 2021-03-20 03:10
Could you try to add a ``std::cout << msg->GetName() << std::endl;`` just after this line?

https://github.com/adepierre/Botcraft/blob/78793e1a8cde90882a48c5c706d8282df3af94c3/botcraft/src/Network/NetworkManager.cpp#L218

This way the last packet printed in the console would be the one with the read error.

Thanks!

**Comment by adepierre** [comment] 2021-03-21 15:22
I think I know what is going on here. The first time you built botcraft, did you also ``cmake install`` it without changing the default path? If so, the old version of the library is installed on your system, and whenever you compile a new example, it loads this old library instead of the new one (i.e. with the ``ReadString`` error and the missing ``Connect`` function).

To solve this you should first try to remove the old version of Botcraft that is probably in your ``/usr/local`` directory.

**Comment by adepierre** [comment] 2021-03-29 10:25
Closing it because there is not much I can do without further information. Feel free to reopen it when you have news about it.

**Closed by adepierre** 2021-03-29 10:25 UTC
Labels: can't reproduce
